[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000
  publish = "dist/web-app/browser"
  jwtRolePath = "app_metadata.authorization.roles"
  jwtSecret = "MY_JWT_SECRET_VALUE"
  autoLaunch = true
  framework = "#custom"
  [dev.https]
    certFile = "cert.pem"
    keyFile = "key.pem"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200